# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TapUIKit-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'MOLH'
  pod 'TapThemeManager2020'
  pod 'SheetyColors'
  pod 'TapApplePayKit-iOS'
  # Pods for TapUIKit-Example

end

target 'TapUIKit-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapUIKit-iOS
  pod 'SnapKit'
  pod 'TapThemeManager2020'
  pod 'MOLH'
  pod 'LocalisationManagerKit-iOS'
  pod 'CommonDataModelsKit-iOS'
  pod 'PullUpController'
  pod "SimpleAnimation"
  pod 'Nuke'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'TapApplePayKit-iOS'
end
