# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TapUIKit-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MOLH'
  pod 'TapThemeManager2020'
  pod 'SheetyColors'
  pod 'TapApplePayKit-iOS'
  pod 'TapCardVlidatorKit-iOS'
  pod 'CommonDataModelsKit-iOS'
  # Pods for TapUIKit-Example

end

target 'TapUIKit-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapUIKit-iOS
  pod 'SnapKit'
  pod 'TapThemeManager2020'
  pod 'MOLH'
  pod 'LocalisationManagerKit-iOS'
  pod 'CommonDataModelsKit-iOS'
  pod 'PullUpController'
  pod 'Nuke'
  pod 'TapApplePayKit-iOS'
  pod 'TapCardVlidatorKit-iOS'
  pod 'TapCardInputKit-iOS'
  pod 'TapCardScanner-iOS'
  pod 'McPicker'
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
end
